const sourceVideos=window.portfolioVideos||[];
const order=[6,10,1,7,11,0,8,12,2,9,13,3,14,4,5];
const videos=order.map(i=>sourceVideos[i]).filter(Boolean);
const gallery=document.querySelector('#gallery');
const empty=document.querySelector('#empty');
const dialog=document.querySelector('#player');
const frame=document.querySelector('#video-frame');
function openVideo(video){document.querySelector('#player-title').textContent=video.title;frame.src=`https://drive.google.com/file/d/${encodeURIComponent(video.driveId)}/preview`;document.querySelector('#drive-link').href=`https://drive.google.com/file/d/${encodeURIComponent(video.driveId)}/view`;dialog.showModal();}
function render(category){gallery.replaceChildren();const selected=videos.filter(v=>category==='All work'||v.category===category);empty.hidden=selected.length>0;document.querySelector('#category-label').textContent=category==='All work'?'THE COLLECTION':category.toUpperCase();document.querySelector('#empty-title').textContent=category==='All work'?'The work belongs here.':category;document.querySelector('#empty-text').textContent=category==='All work'?'Videos are being added to this portfolio.':'Videos in this category will appear here once the collection is reviewed.';for(const v of selected){const card=document.createElement('article');card.className='video-card';const button=document.createElement('button');button.setAttribute('aria-label',`Play ${v.title}`);const img=document.createElement('img');img.src=v.thumbnail||`https://drive.google.com/thumbnail?id=${encodeURIComponent(v.driveId)}&sz=w1200`;img.alt=v.title;img.loading='lazy';img.addEventListener('error',()=>{img.hidden=true});const play=document.createElement('span');play.className='play';play.textContent='▷';play.setAttribute('aria-hidden','true');button.append(img,play);if(v.duration){const time=document.createElement('span');time.className='video-duration';time.textContent=v.duration;button.append(time);}button.addEventListener('click',()=>openVideo(v));const title=document.createElement('h3');title.textContent=v.title;const label=document.createElement('p');label.textContent=v.category;card.append(button,title,label);gallery.append(card);}}
for(const button of document.querySelectorAll('[data-category]'))button.addEventListener('click',()=>{for(const other of document.querySelectorAll('[data-category]')){const active=button===other;other.classList.toggle('active',active);other.setAttribute('aria-pressed',String(active));}render(button.dataset.category);});
document.querySelector('#close-player').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{frame.src='about:blank'});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});for(const b of document.querySelectorAll('[data-category]')){const count=videos.filter(v=>b.dataset.category==='All work'||v.category===b.dataset.category).length;b.textContent+=` · ${count}`;}render('All work');

const featuredVideos=[sourceVideos[6],sourceVideos[0],sourceVideos[10]];let featuredIndex=0;
const featuredPicker=document.querySelector('#featured-picker');
featuredVideos.forEach((v,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`Feature ${v.title}`);const img=document.createElement('img');img.src=v.thumbnail;img.alt='';b.append(img);b.addEventListener('click',()=>setFeatured(i));featuredPicker.append(b);});
function setFeatured(i){featuredIndex=(i+featuredVideos.length)%featuredVideos.length;const v=featuredVideos[featuredIndex];document.querySelector('#featured-image').src=v.thumbnail;document.querySelector('#featured-image').alt=v.title;document.querySelector('#featured-title').textContent=v.title;document.querySelector('#featured-category').textContent=v.category;document.querySelector('#featured-count').textContent=`0${featuredIndex+1} / 03`;document.querySelector('#featured-card').setAttribute('aria-label',`Play ${v.title}`);[...featuredPicker.children].forEach((b,n)=>b.setAttribute('aria-pressed',String(n===featuredIndex)));}
document.querySelector('#featured-prev').addEventListener('click',()=>setFeatured(featuredIndex-1));document.querySelector('#featured-next').addEventListener('click',()=>setFeatured(featuredIndex+1));document.querySelector('#featured-card').addEventListener('click',()=>openVideo(featuredVideos[featuredIndex]));setFeatured(0);

const aboutDialog=document.querySelector('#about-dialog');
document.querySelector('#more-about').addEventListener('click',()=>aboutDialog.showModal());
document.querySelector('#close-about').addEventListener('click',()=>aboutDialog.close());
document.querySelector('#about-work').addEventListener('click',()=>{aboutDialog.close();location.hash='work';});
