(()=>{
  if(window.__storyboardUiInit)return; window.__storyboardUiInit=true;
  const $=id=>document.getElementById(id);
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  let currentMode='product', productFlow='story', productImageSource='', lastData=null;
  const shotBanks={
    balanced:[['Establishing wide','slow push-in','6s','set environment and tone'],['Medium interaction','gentle handheld drift','7s','show body language and action'],['Close-up','subtle static hold','5s','capture emotion and detail'],['Insert detail','micro push','4s','highlight a key object or action']],
    cinematic:[['Cinematic master','slow dolly-in','6s','introduce atmosphere and geography'],['Over-shoulder medium','motivated slider move','7s','show character relationship'],['Tight close-up','locked micro-motion','5s','land the emotional beat'],['Cutaway detail','slow macro glide','4s','emphasize texture or prop']],
    commercial:[['Hero wide','smooth gimbal move','5s','create premium product context'],['Product action medium','slow arc move','6s','show product use clearly'],['Beauty close-up','micro push-in','4s','feature product or face'],['Macro detail','controlled macro move','4s','show material and finish']],
    social:[['Hook shot','quick clean push-in','3s','grab attention'],['Action medium','light handheld energy','5s','deliver main beat fast'],['Reaction close-up','static hold','4s','show impact'],['Support detail','quick insert move','3s','reinforce the message']]
  };

  function toast(message,type='success'){
    const el=document.createElement('div'); el.className=`toast ${type}`; el.textContent=message; $('toastWrap').appendChild(el); setTimeout(()=>{el.style.opacity='0';setTimeout(()=>el.remove(),180)},2200);
  }
  function setStep(n){[1,2,3,4].forEach(i=>{const el=$(`step${i}`);el.className='step'+(i<n?' done':i===n?' active':'')})}
  function setMode(mode){currentMode=mode; qa('.tab').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode)); qa('.modeSection').forEach(s=>s.classList.remove('active')); $(`${mode}Mode`).classList.add('active'); $('modeLabel').textContent=mode[0].toUpperCase()+mode.slice(1)+' mode';}
  qa('.tab').forEach(btn=>btn.addEventListener('click',()=>setMode(btn.dataset.mode)));
  qa('.choice').forEach(btn=>btn.addEventListener('click',()=>{productFlow=btn.dataset.flow;qa('.choice').forEach(x=>x.classList.remove('active'));btn.classList.add('active');}));
  qa('.navBtn').forEach(btn=>btn.addEventListener('click',()=>{qa('.navBtn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$(btn.dataset.scroll).scrollIntoView({behavior:'smooth',block:'start'});}));

  const dropzone=$('dropzone'),fileInput=$('productImageFile');
  ['dragenter','dragover'].forEach(evt=>dropzone.addEventListener(evt,e=>{e.preventDefault();dropzone.classList.add('drag')}));
  ['dragleave','drop'].forEach(evt=>dropzone.addEventListener(evt,e=>{e.preventDefault();dropzone.classList.remove('drag')}));
  dropzone.addEventListener('drop',e=>{const f=e.dataTransfer.files&&e.dataTransfer.files[0];if(f)loadProductFile(f)});
  fileInput.addEventListener('change',e=>{const f=e.target.files&&e.target.files[0];if(f)loadProductFile(f)});
  function loadProductFile(file){if(!file.type.startsWith('image/')){toast('Please choose an image file','error');return;}if(file.size>12*1024*1024){toast('Image is too large (max 12 MB)','error');return;}const r=new FileReader();r.onload=e=>{productImageSource=e.target.result;$('productPreview').src=productImageSource;$('productPreviewName').textContent=file.name;$('productPreviewWrap').classList.add('show');setStep(1);toast('Product reference added')};r.readAsDataURL(file)}
  $('removeImage').addEventListener('click',()=>{productImageSource='';fileInput.value='';$('productPreviewWrap').classList.remove('show');$('productPreview').src='';});

  function values(){return{
    projectName:$('projectName').value.trim()||'Untitled storyboard',style:$('style').value,model:$('model').value,ratio:$('ratio').value,mood:$('mood').value.trim()||'premium, natural, cinematic',shotCount:Math.max(1,Math.min(5,Number($('shotCount').value)||3)),camera:$('camera').value,detail:$('detail').value,productFlow,
    productName:$('productName').value.trim(),productCategory:$('productCategory').value.trim(),productBenefits:$('productBenefits').value.trim(),targetAudience:$('targetAudience').value.trim(),offerCta:$('offerCta').value.trim(),script:$('script').value.trim(),characters:$('characters').value.trim()||'Maintain consistent character identity, age, hair, wardrobe and accessories.',environment:$('environment').value.trim()||'Maintain consistent location geography, lighting, set dressing and props.',rules:$('rules').value.trim()||'Preserve continuity, natural movement, coherent screen direction, no random text or watermark.',productImageSource
  }}
  function parseScenes(text){return text.split(/\n\s*\n+/).map(x=>x.trim()).filter(Boolean).map((block,i)=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean),first=lines[0]||`Scene ${i+1}`,heading=/^(hook|scene\s*\d+|scene\s*[a-z]+|intro|outro|ending)/i.test(first),speakers=[...new Set(lines.map(l=>(l.match(/^([A-Za-z][A-Za-z\s'.-]{1,30}):/)||[])[1]).filter(Boolean))];return{id:i+1,title:heading?first:`Scene ${String(i+1).padStart(2,'0')}`,description:heading?lines.slice(1).join(' '):lines.join(' '),speakers}})}
  function productScenes(v){const hook={story:'Open with an emotionally relatable moment before revealing the product.',ugc:'Open with a quick personal reaction or problem statement.',demo:'Open with the product immediately and state the core use case visually.',launch:'Open with a polished hero reveal and premium brand energy.'};const reveal={story:'Bring the product naturally into the story as the turning point.',ugc:'Introduce the product casually as the creator’s discovery.',demo:'Show exactly what the product is and how it is used.',launch:'Reveal packaging, silhouette and product details with premium motion.'};return[
    {title:'Hook / opener',goal:hook[v.productFlow],visual:'Attention-grabbing human, lifestyle or product-first opening.',beat:`Create curiosity for ${v.targetAudience||'the target audience'} around ${v.productBenefits||v.productName||'the main product benefit'}.`},
    {title:'Product reveal',goal:reveal[v.productFlow],visual:'Hero reveal, in-hand shot, packaging detail or product placement.',beat:`Reveal ${v.productName||'the product'} clearly and establish its category and visual identity.`},
    {title:'Benefit demonstration',goal:'Show why the product is useful, desirable or different.',visual:'Application, demo, result, texture or functional close-up.',beat:`Feature the strongest benefits: ${v.productBenefits||'clarify the top selling points'}.`},
    {title:'Lifestyle moment',goal:'Show the product in a believable real-life context.',visual:'Routine, desk, vanity, café, gym, outdoor or social environment.',beat:`Place ${v.productName||'the product'} naturally into a moment relevant to ${v.targetAudience||'the audience'}.`},
    {title:'Proof / detail',goal:'Build confidence with a result, detail, finish or credibility moment.',visual:'Macro product detail, result shot, reaction, feature close-up or proof point.',beat:'Reinforce quality and make the promised outcome feel tangible.'},
    {title:'CTA / end frame',goal:'End with a memorable hero image and clear next step.',visual:'Premium end frame with product and brand mood.',beat:v.offerCta||'Invite the viewer to discover the product, shop, or learn more.'}
  ]}
  function shorten(text,level){const t=(text||'').replace(/\s+/g,' ').trim(),n=level==='compact'?190:level==='medium'?340:9999;return t.length>n?t.slice(0,n)+'…':t}
  function buildShots(scene,v){const bank=shotBanks[v.camera]||shotBanks.cinematic;return Array.from({length:v.shotCount},(_,i)=>{const b=bank[i%bank.length],label=`Scene ${String(scene.id).padStart(2,'0')} · Shot ${String(i+1).padStart(2,'0')}`,summary=shorten(scene.description,v.detail),speaker=scene.speakers.length?`Featured characters: ${scene.speakers.join(', ')}.`:'Use the most relevant character or product interaction for this beat.',product=v.productName?`Product focus: ${v.productName}${v.productCategory?` (${v.productCategory})`:''}.`:'';return{label,type:b[0],move:b[1],duration:b[2],purpose:b[3],imagePrompt:`${v.ratio} ${v.style} storyboard frame optimized for ${v.model}. ${label}. ${b[0]}. Scene objective: ${b[3]}. Story beat: ${summary} ${speaker} ${product} ${v.productImageSource?'Use the uploaded product reference as an exact visual anchor for product silhouette, packaging, material, colors, proportions and details.':'Keep the product appearance coherent and premium across every frame.'} Mood: ${v.mood}. Product benefits: ${v.productBenefits||'make the strongest benefit visually clear'}. Audience: ${v.targetAudience||'intended audience'}. Character lock: ${v.characters} Environment lock: ${v.environment} Global rules: ${v.rules} Camera direction: ${b[1]}.`,videoPrompt:`Continue directly from the matching storyboard image for ${label}. Duration: ${b[2]}. Camera: ${b[0]} with ${b[1]}. Action: ${summary} ${speaker} ${product} Preserve character identity, wardrobe, product appearance, environment geography, prop placement, lighting and screen direction. Use natural motivated movement only. Do not introduce identity drift, packaging drift, background drift, random text or abrupt camera jumps. Global rules: ${v.rules}`}})}
  function storyboardFromProduct(v){const plan=productScenes(v),auto=plan.map((s,i)=>`SCENE ${i+1}\n${s.title}: ${s.goal} ${s.visual} ${s.beat}`).join('\n\n');return{plan,scenes:parseScenes(auto).map(s=>({...s,shots:buildShots(s,v)}))}}
  function storyboardFromScript(v){const scenes=parseScenes(v.script);return{plan:null,scenes:scenes.map(s=>({...s,shots:buildShots(s,v)}))}}

  function render(data,v){const root=$('resultsArea');root.innerHTML='';const list=document.createElement('div');list.className='sceneList';data.scenes.forEach((scene,si)=>{const detail=document.createElement('details');detail.className='sceneCard';if(si===0)detail.open=true;const summary=document.createElement('summary');summary.className='sceneSummary';summary.innerHTML=`<div class="sceneNum">${String(si+1).padStart(2,'0')}</div><div class="sceneMeta"><strong>${escapeHtml(scene.title)}</strong><span>${escapeHtml(scene.description||'Storyboard scene')}</span></div><div class="sceneBadges"><span class="badge">${scene.shots.length} shots</span><span class="badge">${escapeHtml(v.ratio)}</span></div><div class="chev">⌄</div>`;detail.appendChild(summary);const body=document.createElement('div');body.className='sceneBody';const grid=document.createElement('div');grid.className='shotsGrid';scene.shots.forEach((shot,idx)=>grid.appendChild(renderShot(shot,idx,v)));body.appendChild(grid);detail.appendChild(body);list.appendChild(detail)});root.appendChild(list);setStep(3);$('statusBox').innerHTML=`<b>Storyboard ready.</b> ${data.scenes.length} scenes and ${data.scenes.reduce((n,s)=>n+s.shots.length,0)} shots created.`;toast('Storyboard generated')}
  function renderShot(shot,idx,v){const card=document.createElement('article');card.className='shotCard';const visual=document.createElement('div');visual.className='shotVisual';if(v.productImageSource){const img=document.createElement('img');img.src=v.productImageSource;img.alt='Product reference';visual.appendChild(img)}else visual.textContent='Storyboard frame preview';const num=document.createElement('span');num.className='shotNo';num.textContent=`Shot ${idx+1}`;visual.appendChild(num);const info=document.createElement('div');info.className='shotInfo';info.innerHTML=`<div class="shotTop"><strong>${escapeHtml(shot.type)}</strong><span>${escapeHtml(shot.duration)}</span></div><div class="shotSpec">${escapeHtml(shot.move)} · ${escapeHtml(shot.purpose)}</div>`;const tabs=document.createElement('div');tabs.className='promptTabs';const imgTab=document.createElement('button');imgTab.className='promptTab active';imgTab.textContent='Image prompt';const vidTab=document.createElement('button');vidTab.className='promptTab';vidTab.textContent='Video prompt';tabs.append(imgTab,vidTab);const box=document.createElement('div');box.className='promptBox';box.textContent=shot.imagePrompt;imgTab.addEventListener('click',()=>{imgTab.classList.add('active');vidTab.classList.remove('active');box.textContent=shot.imagePrompt});vidTab.addEventListener('click',()=>{vidTab.classList.add('active');imgTab.classList.remove('active');box.textContent=shot.videoPrompt});const actions=document.createElement('div');actions.className='promptActions';const copy=document.createElement('button');copy.textContent='Copy current';copy.addEventListener('click',()=>copyText(box.textContent));const copyBoth=document.createElement('button');copyBoth.textContent='Copy both';copyBoth.addEventListener('click',()=>copyText(`IMAGE PROMPT\n${shot.imagePrompt}\n\nVIDEO PROMPT\n${shot.videoPrompt}`));actions.append(copy,copyBoth);info.append(tabs,box,actions);card.append(visual,info);return card}
  function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  async function copyText(text){try{await navigator.clipboard.writeText(text);toast('Copied to clipboard')}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Copied to clipboard')}}
  function allPromptText(){if(!lastData)return'';return lastData.data.scenes.map(scene=>`${scene.title}\n${scene.description}\n\n`+scene.shots.map(s=>`${s.label}\nIMAGE PROMPT\n${s.imagePrompt}\n\nVIDEO PROMPT\n${s.videoPrompt}`).join('\n\n')).join('\n\n==============================\n\n')}

  $('generateBtn').addEventListener('click',()=>{const v=values();let data;if(currentMode==='script'||v.script){if(!v.script){toast('Paste a script first','error');setMode('script');return;}data=storyboardFromScript(v)}else{if(!v.productName&&!v.productCategory&&!v.productBenefits){toast('Add product details first','error');setMode('product');return;}data=storyboardFromProduct(v)}lastData={v,data};setStep(2);$('statusBox').innerHTML='<b>Directing shots…</b> Building scene flow, camera language and continuity prompts.';setTimeout(()=>render(data,v),180)});
  $('copyAllBtn').addEventListener('click',()=>{if(!lastData){toast('Generate a storyboard first','error');return;}copyText(allPromptText());setStep(4)});
  $('exportBtn').addEventListener('click',()=>{if(!lastData){toast('Generate a storyboard first','error');return;}const blob=new Blob([JSON.stringify({project:lastData.v.projectName,settings:lastData.v,storyboard:lastData.data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=(lastData.v.projectName||'storyboard').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'.json';a.click();URL.revokeObjectURL(url);setStep(4);toast('JSON exported')});
  $('saveBtn').addEventListener('click',()=>{const v=values();try{const safe={...v,productImageSource:v.productImageSource&&v.productImageSource.length<900000?v.productImageSource:''};localStorage.setItem('storyboard-ai-v3',JSON.stringify(safe));toast('Draft saved')}catch{toast('Draft is too large to save locally','error')}});
  function loadSaved(){try{const v=JSON.parse(localStorage.getItem('storyboard-ai-v3')||'null');if(!v)return;Object.entries(v).forEach(([k,val])=>{const el=$(k);if(el&&['INPUT','TEXTAREA','SELECT'].includes(el.tagName)&&k!=='productImageSource')el.value=val});if(v.productFlow){productFlow=v.productFlow;qa('.choice').forEach(b=>b.classList.toggle('active',b.dataset.flow===productFlow))}if(v.productImageSource){productImageSource=v.productImageSource;$('productPreview').src=productImageSource;$('productPreviewName').textContent='Saved product reference';$('productPreviewWrap').classList.add('show')}}catch{}}
  $('resetBtn').addEventListener('click',()=>{if(!confirm('Reset this storyboard project?'))return;localStorage.removeItem('storyboard-ai-v3');location.reload()});
  $('sampleBtn').addEventListener('click',()=>{$('projectName').value='TrueTone Product Story';$('style').value='Cinematic Realistic';$('model').value='Google Flow / Veo';$('ratio').value='9:16';$('mood').value='premium, emotional, polished beauty storytelling';$('productName').value='TrueTone Lipstick';$('productCategory').value='pH-adjusting lipstick';$('productBenefits').value='custom-looking color, elegant gold packaging, smooth finish, long-lasting wear';$('targetAudience').value='women who prefer elegant, effortless beauty products';$('offerCta').value='Discover your shade';$('characters').value='Carol — female, 65–70, silver-grey layered bob, pearl stud earrings, elegant muted blouse. Preserve her exact age, face, hair and wardrobe across all scenes.';$('environment').value='Warm premium interiors with believable practical lighting; maintain exact room geography within each scene.';$('rules').value='Natural storytelling, no direct lens gaze unless motivated, realistic faces, consistent product geometry, no random text or watermark.';setMode('product');toast('Sample loaded')});
  loadSaved();
})();
